# Generated by Django 3.2.5 on 2021-07-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HammingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_even', models.BooleanField()),
                ('sequence', models.CharField(max_length=124)),
            ],
        ),
    ]
